import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { fetchStrapi } from "@/src/lib/strapi";
import type { GlobalSettings, StrapiSingleResponse } from "@/src/types/strapi";
import { Footer } from "@/src/layout/footer";
import { Header } from "@/src/layout/header";
import { ModalProvider } from "@/src/providers/modal-provider";
import { SectionIndicator } from "@/src/components/section-indicator";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

async function getGlobal() {
    return fetchStrapi<StrapiSingleResponse<GlobalSettings>>(
        "/api/global"
    );
}

export const metadata: Metadata = {
    title: "Site",
    description: "Generated by Next.js",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const globalRes = await getGlobal();
    const global = globalRes.data;

    return (
        <html lang="ru">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#383838] text-white`}
        >
        <ModalProvider telegramBotUrl={process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL || global.telegramBotUrl}>
        <SectionIndicator />
        <Header global={global} />
        {children}
        <Footer global={global} />
        </ModalProvider>
        </body>
        </html>
    );
}